import React, { useEffect, useMemo, useState } from "react";
import { IssueReport } from "../types";
import { ArrowLeft, CheckCircle, Copy, Clock, Layers, Sparkles, Download, AlertTriangle, Trophy, Medal } from "lucide-react";
import { ISSUE_STATUS_KEYS, IssueStatusKey, issueStatusLabel } from "../constants/status";
import { isInternalSmokeTestIssue } from "../utils/issueVisibility";

interface ImpactDashboardProps {
  issues: IssueReport[];
  onBack: () => void;
  hasMoreIssues?: boolean;
  loadedPageSize?: number;
}

type DashboardScope = "real" | "demo";

const categories = ["pothole", "water_leak", "streetlight", "waste", "drainage", "road_damage", "other"];
const statuses = ISSUE_STATUS_KEYS;
const MIN_RATE_DENOMINATOR = 3;

function parseStoredDate(value?: string): number | null {
  if (!value) return null;
  const parsed = Date.parse(value);
  return Number.isNaN(parsed) ? null : parsed;
}

function formatMetricUnavailable(reason: string) {
  return {
    value: "Not enough data",
    detail: reason,
  };
}

function buildMetrics(issues: IssueReport[]) {
  const totalReported = issues.length;
  const totalResolved = issues.filter((issue) => issue.status === "resolved").length;
  const resolutionRate = totalReported >= MIN_RATE_DENOMINATOR
    ? {
        value: `${Math.round((totalResolved / totalReported) * 100)}%`,
        detail: "Resolved among loaded records",
      }
    : formatMetricUnavailable(`Need at least ${MIN_RATE_DENOMINATOR} loaded records`);

  const resolutionDurations = issues.flatMap((issue) => {
    const createdAt = parseStoredDate(issue.createdAt || issue.timestamp);
    const resolvedAt = parseStoredDate(issue.resolvedAt);
    if (!createdAt || !resolvedAt || resolvedAt < createdAt) return [];
    return [(resolvedAt - createdAt) / (1000 * 60 * 60 * 24)];
  });
  const avgResolutionTime = resolutionDurations.length > 0
    ? {
        value: `${(resolutionDurations.reduce((sum, days) => sum + days, 0) / resolutionDurations.length).toFixed(1)}d`,
        detail: `${resolutionDurations.length} resolved record${resolutionDurations.length === 1 ? "" : "s"} with stored timestamps`,
      }
    : formatMetricUnavailable("No resolved records with stored created/resolved timestamps");

  const totalDuplicates = issues.reduce((acc, curr) => {
    const count = curr.reportCount || 1;
    return acc + Math.max(0, count - 1);
  }, 0);

  const categoryCounts = categories.reduce((acc, cat) => {
    acc[cat] = issues.filter((issue) => issue.category === cat).length;
    return acc;
  }, {} as Record<IssueStatusKey, number>);

  const statusCounts = statuses.reduce((acc, stat) => {
    acc[stat] = issues.filter((issue) => issue.status === stat).length;
    return acc;
  }, {} as Record<string, number>);

  return {
    totalReported,
    totalResolved,
    resolutionRate,
    avgResolutionTime,
    totalDuplicates,
    categoryCounts,
    statusCounts,
  };
}

export default function ImpactDashboard({
  issues,
  onBack,
  hasMoreIssues = false,
  loadedPageSize = 50,
}: ImpactDashboardProps) {
  const [scope, setScope] = useState<DashboardScope>("real");
  const publicIssues = useMemo(() => issues.filter((issue) => !isInternalSmokeTestIssue(issue)), [issues]);
  const realIssues = useMemo(() => publicIssues.filter((issue) => !issue.isDemoData), [publicIssues]);
  const demoIssues = useMemo(() => publicIssues.filter((issue) => issue.isDemoData), [publicIssues]);
  const scopedIssues = scope === "real" ? realIssues : demoIssues;
  const metrics = useMemo(() => buildMetrics(scopedIssues), [scopedIssues]);
  const maxCategoryCount = Math.max(...Object.values(metrics.categoryCounts), 1);
  const maxStatusCount = Math.max(...Object.values(metrics.statusCounts), 1);

  const scopeOptions: { id: DashboardScope; label: string; count: number }[] = [
    { id: "real", label: "Real records", count: realIssues.length },
    { id: "demo", label: "Synthetic demo", count: demoIssues.length },
  ];

  // Open civic analytics: predictive insight generated by the server worker.
  const [insight, setInsight] = useState<any>(null);
  const [insightLoading, setInsightLoading] = useState(true);
  useEffect(() => {
    let active = true;
    fetch("/api/insights/predictive")
      .then((r) => (r.ok ? r.json() : null))
      .then((d) => { if (active) setInsight(d?.insight ? d : null); })
      .catch(() => { if (active) setInsight(null); })
      .finally(() => { if (active) setInsightLoading(false); });
    return () => { active = false; };
  }, []);

  // Public community leaderboard (gamification).
  const [leaders, setLeaders] = useState<any[]>([]);
  useEffect(() => {
    let active = true;
    fetch("/api/leaderboard")
      .then((r) => (r.ok ? r.json() : null))
      .then((d) => { if (active) setLeaders(Array.isArray(d?.leaders) ? d.leaders : []); })
      .catch(() => { if (active) setLeaders([]); });
    return () => { active = false; };
  }, []);

  const handleExportOpen311 = async () => {
    try {
      const res = await fetch("/api/export/open311");
      const data = await res.json();
      const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url; a.download = "civiclens-open311.json"; a.click();
      URL.revokeObjectURL(url);
    } catch { /* no-op: export is best-effort */ }
  };

  return (
    <div id="impact-dashboard" className="mx-auto flex w-full max-w-6xl flex-col gap-6 p-4 bg-paper min-h-screen font-sans pb-28 text-ink sm:p-6 lg:p-8">
      <div className="flex items-center gap-3">
        <button
          type="button"
          onClick={onBack}
          className="flex items-center justify-center w-11 h-11 rounded-full bg-white border border-hairline shadow-2xs cursor-pointer hover:bg-paper transition-all"
          title="Back to Landing"
          aria-label="Back to landing page"
        >
          <ArrowLeft className="w-4 h-4 text-ink" />
        </button>
        <div>
          <span className="text-sm font-mono text-slate block">Pilot impact dashboard</span>
          <h2 className="text-3xl font-display font-black text-ink">Loaded incident ledger</h2>
        </div>
      </div>

      <div className="bg-white border border-hairline rounded-2xl p-3 shadow-xs flex flex-col gap-3">
        <div className="flex flex-wrap gap-2">
          {scopeOptions.map((option) => (
            <button
              key={option.id}
              type="button"
              onClick={() => setScope(option.id)}
              aria-pressed={scope === option.id}
              className={`min-h-[44px] rounded-xl border px-4 text-base font-bold ${
                scope === option.id
                  ? "bg-ink text-paper border-ink"
                  : "bg-paper text-slate border-hairline hover:text-ink"
              }`}
            >
              {option.label} ({option.count})
            </button>
          ))}
        </div>
        <p className="text-base text-slate leading-relaxed">
          Metrics are computed only from the {scopedIssues.length} {scope === "real" ? "real" : "synthetic demo"} records currently loaded.
          {hasMoreIssues ? ` More records may exist beyond the loaded page of ${loadedPageSize}.` : " The current query reports no additional page."}
        </p>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mt-1">
        <div className="bg-white p-3.5 rounded-2xl border border-hairline flex flex-col gap-1 shadow-[0_2px_8px_-2px_rgba(14,26,43,0.04)]">
          <div className="flex items-center gap-1 text-slate">
            <Layers className="w-3.5 h-3.5 text-slate shrink-0" />
            <span className="text-sm font-mono">Loaded records</span>
          </div>
          <span className="text-4xl font-mono font-bold text-ink leading-tight mt-0.5">{metrics.totalReported}</span>
          <span className="text-sm text-slate font-medium leading-tight">{scope === "demo" ? "Synthetic demo records" : "Non-demo records"}</span>
        </div>

        <div className="bg-white p-3.5 rounded-2xl border border-hairline flex flex-col gap-1 shadow-[0_2px_8px_-2px_rgba(14,26,43,0.04)]">
          <div className="flex items-center gap-1 text-verify">
            <CheckCircle className="w-3.5 h-3.5 text-verify shrink-0" />
            <span className="text-sm font-mono">Resolved rate</span>
          </div>
          <span className="text-3xl font-mono font-bold text-verify leading-tight mt-0.5">{metrics.resolutionRate.value}</span>
          <span className="text-sm text-slate font-medium leading-tight">{metrics.resolutionRate.detail}</span>
        </div>

        <div className="bg-white p-3.5 rounded-2xl border border-hairline flex flex-col gap-1 shadow-[0_2px_8px_-2px_rgba(14,26,43,0.04)]">
          <div className="flex items-center gap-1 text-slate">
            <Clock className="w-3.5 h-3.5 text-slate shrink-0" />
            <span className="text-sm font-mono">Resolution time</span>
          </div>
          <span className="text-3xl font-mono font-bold text-ink leading-tight mt-0.5">{metrics.avgResolutionTime.value}</span>
          <span className="text-sm text-slate font-medium leading-tight">{metrics.avgResolutionTime.detail}</span>
        </div>

        <div className="bg-white p-3.5 rounded-2xl border border-hairline flex flex-col gap-1 shadow-[0_2px_8px_-2px_rgba(14,26,43,0.04)]">
          <div className="flex items-center gap-1 text-marigold">
            <Copy className="w-3.5 h-3.5 text-marigold shrink-0" />
            <span className="text-sm font-mono">Consolidated</span>
          </div>
          <span className="text-4xl font-mono font-bold text-ink leading-tight mt-0.5">{metrics.totalDuplicates}</span>
          <span className="text-sm text-slate font-medium leading-tight">Stored duplicate count signals</span>
        </div>
      </div>

      <div className="bg-white border border-hairline rounded-2xl p-4 shadow-[0_4px_16px_-4px_rgba(14,26,43,0.05)] flex flex-col gap-3">
        <h3 className="text-lg font-bold text-ink border-b border-hairline pb-2">Category distribution</h3>
        <div className="flex flex-col gap-3">
          {categories.map((cat) => {
            const count = metrics.categoryCounts[cat] || 0;
            const pct = count === 0 ? 0 : Math.max(6, Math.round((count / maxCategoryCount) * 100));
            return (
              <div key={cat} className="flex flex-col gap-1 text-sm">
                <div className="flex items-center justify-between text-slate font-semibold">
                  <span className="text-sm font-medium text-ink">{cat.replace("_", " ")}</span>
                  <span className="font-mono text-ink text-sm">{count}</span>
                </div>
                <div className="w-full bg-paper h-1.5 rounded-full overflow-hidden border border-hairline">
                  <div className="bg-marigold h-full rounded-full transition-all duration-300" style={{ width: `${pct}%` }} />
                </div>
              </div>
            );
          })}
        </div>
      </div>

      <div className="bg-white border border-hairline rounded-2xl p-4 shadow-[0_4px_16px_-4px_rgba(14,26,43,0.05)] flex flex-col gap-3">
        <h3 className="text-lg font-bold text-ink border-b border-hairline pb-2">Status lifecycles</h3>
        <div className="flex flex-col gap-3">
          {statuses.map((stat) => {
            const count = metrics.statusCounts[stat] || 0;
            const pct = count === 0 ? 0 : Math.max(6, Math.round((count / maxStatusCount) * 100));
            const statusBarColors: Record<IssueStatusKey, string> = {
              submitted: "bg-slate",
              verified: "bg-marigold",
              in_progress: "bg-[#3B82F6]",
              resolved: "bg-verify",
            };

            return (
              <div key={stat} className="flex flex-col gap-1 text-sm">
                <div className="flex items-center justify-between text-slate font-semibold">
                  <span className="text-sm font-medium text-ink">{issueStatusLabel(stat)}</span>
                  <span className="font-mono text-ink text-sm">{count}</span>
                </div>
                <div className="w-full bg-paper h-1.5 rounded-full overflow-hidden border border-hairline">
                  <div className={`${statusBarColors[stat] || "bg-slate"} h-full rounded-full transition-all duration-300`} style={{ width: `${pct}%` }} />
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Predictive insights (Gemini forecast over real aggregates) + Open311 export */}
      <div className="bg-white border border-hairline rounded-2xl p-4 shadow-[0_4px_16px_-4px_rgba(14,26,43,0.05)] flex flex-col gap-3">
        <div className="flex items-center justify-between gap-3 border-b border-hairline pb-2">
          <h3 className="flex items-center gap-2 text-lg font-bold text-ink">
            <Sparkles className="w-5 h-5 text-marigold" aria-hidden="true" />
            Predictive insights
          </h3>
          <button
            onClick={handleExportOpen311}
            className="inline-flex items-center gap-1.5 rounded-xl border border-hairline bg-paper px-3 py-2 text-sm font-semibold text-ink min-h-[40px] hover:bg-white"
            aria-label="Export all records as Open311 GeoReport v2 JSON"
          >
            <Download className="w-4 h-4" aria-hidden="true" />
            Open311 export
          </button>
        </div>
        {insightLoading ? (
          <div className="h-20 rounded-xl bg-paper animate-pulse" aria-label="Loading predictive insights" />
        ) : !insight?.insight ? (
          <p className="text-sm text-slate">No predictive briefing yet. An operator can generate one from the agency desk.</p>
        ) : (
          <div className="flex flex-col gap-3">
            <p className="text-sm text-ink-2 leading-relaxed">{insight.insight.summary}</p>
            {Array.isArray(insight.insight.priorityCategories) && insight.insight.priorityCategories.length > 0 && (
              <div className="flex flex-wrap items-center gap-2">
                <span className="text-sm font-semibold text-slate">Priority categories:</span>
                {insight.insight.priorityCategories.map((c: string) => (
                  <span key={c} className="rounded-full bg-marigold/10 px-2.5 py-1 text-sm font-semibold text-marigold-ink">{String(c).replace(/_/g, " ")}</span>
                ))}
              </div>
            )}
            {Array.isArray(insight.insight.predictedHotspots) && insight.insight.predictedHotspots.length > 0 && (
              <div className="flex flex-col gap-2">
                <span className="text-sm font-semibold text-slate">Predicted hotspots</span>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                  {insight.insight.predictedHotspots.slice(0, 6).map((h: any, i: number) => {
                    const risk = String(h.riskLevel || "medium").toLowerCase();
                    const riskClass = risk === "high" ? "text-alert" : risk === "low" ? "text-verify" : "text-marigold-ink";
                    return (
                      <div key={i} className="rounded-xl border border-hairline bg-paper p-3 flex flex-col gap-1">
                        <div className="flex items-center justify-between">
                          <span className="text-sm font-bold text-ink">{h.area}</span>
                          <span className={`inline-flex items-center gap-1 text-sm font-bold ${riskClass}`}>
                            <AlertTriangle className="w-3.5 h-3.5" aria-hidden="true" />
                            {risk}
                          </span>
                        </div>
                        <span className="text-sm text-slate">{String(h.category).replace(/_/g, " ")}</span>
                        {h.rationale && <span className="text-[13px] text-ink-2 leading-snug">{h.rationale}</span>}
                      </div>
                    );
                  })}
                </div>
              </div>
            )}
            {Array.isArray(insight.insight.recommendedActions) && insight.insight.recommendedActions.length > 0 && (
              <div className="flex flex-col gap-1">
                <span className="text-sm font-semibold text-slate">Recommended actions</span>
                <ul className="list-disc pl-5 text-sm text-ink-2 flex flex-col gap-1">
                  {insight.insight.recommendedActions.slice(0, 4).map((a: string, i: number) => <li key={i}>{a}</li>)}
                </ul>
              </div>
            )}
            {insight.aiFallback && (
              <p className="text-[13px] text-slate italic">Deterministic summary shown (AI forecast temporarily unavailable).</p>
            )}
          </div>
        )}
      </div>

      {/* Community leaderboard (gamified civic engagement) */}
      <div className="bg-white border border-hairline rounded-2xl p-4 shadow-[0_4px_16px_-4px_rgba(14,26,43,0.05)] flex flex-col gap-3">
        <h3 className="flex items-center gap-2 text-lg font-bold text-ink border-b border-hairline pb-2">
          <Trophy className="w-5 h-5 text-marigold" aria-hidden="true" />
          Community leaderboard
        </h3>
        {leaders.length === 0 ? (
          <p className="text-sm text-slate">No contributors yet. Report, support, or verify issues to earn points and badges.</p>
        ) : (
          <ol className="flex flex-col gap-2">
            {leaders.map((l) => (
              <li key={l.rank} className="flex items-center gap-3 rounded-xl border border-hairline bg-paper p-3">
                <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-marigold/10 font-mono text-sm font-bold text-marigold-ink">
                  {l.rank <= 3 ? <Medal className="w-4 h-4 text-marigold" aria-hidden="true" /> : l.rank}
                </span>
                <div className="flex flex-col min-w-0">
                  <span className="text-sm font-bold text-ink truncate">{l.handle}</span>
                  <span className="text-[13px] text-slate">Level {l.level} · {l.reportCount} reports · {l.verifyCount} verifications · Trust {typeof l.trustScore === "number" ? Math.round(l.trustScore * 100) : 32}%</span>
                  {Array.isArray(l.badges) && l.badges.length > 0 && (
                    <div className="mt-1 flex flex-wrap gap-1">
                      {l.badges.map((b: string) => (
                        <span key={b} className="rounded-full bg-verify/10 px-2 py-0.5 text-[13px] font-semibold text-verify">{b}</span>
                      ))}
                    </div>
                  )}
                </div>
                <span className="ml-auto shrink-0 font-mono text-lg font-bold text-ink tabular-nums">{l.points}<span className="text-[13px] font-semibold text-slate"> pts</span></span>
              </li>
            ))}
          </ol>
        )}
      </div>
    </div>
  );
}
